version: '3.3'

services:

   postgres:
   
      image: postgres:14-alpine
      
      restart: always

      ports:
         - 44:5432
         
      volumes:
         - ./postgresdata:/var/lib/postgresql/data
         
      env_file:
         - .env.postgres
   
   dbmaker:
   
      image: ivanduque0/dbmakermanager:V0.3
      
      volumes:
         - ./dbmaker:/app
         
      command: python3 codigo.py
         
      env_file:
         - .env.maker
         
      depends_on:
         - postgres

   dbmanagerfotos:
   
      image: ivanduque0/dbmakermanager:V0.3
      
      restart: always
      
      command: python3 codigo.py
      
      volumes:
         - ./dbmanagerfotos:/app
         
      env_file:
         - .env.manager
         
      depends_on:
         - postgres
         
   dbmanagerusuarios:
   
      image: ivanduque0/dbmakermanager:V0.3
      
      restart: always
      
      command: python3 codigo.py
      
      volumes:
         - ./dbmanagerusuarios:/app
         
      env_file:
         - .env.manager
      
      depends_on:
         - postgres
         
   dbmanagerhorarios:
   
      image: ivanduque0/dbmakermanager:V0.3
      
      restart: always
      
      command: python3 codigo.py
      
      volumes:
         - ./dbmanagerhorarios:/app
         
      env_file:
         - .env.manager
      
      depends_on:
         - postgres
         
   dbmanagerinteracciones:
   
      image: ivanduque0/dbmakermanager:V0.3
      
      restart: always
      
      command: python3 codigo.py
      
      volumes:
         - ./dbmanagerinteracciones:/app
         
      env_file:
         - .env.manager
      
      depends_on:
         - postgres

   dbmanagerid:
   
      image: ivanduque0/dbmakermanager:V0.3
      
      restart: always
      
      command: python3 codigo.py
      
      volumes:
         - ./dbmanagertelegramid:/app
         
      env_file:
         - .env.manager
      
      depends_on:
         - postgres
         
   telegrambot:
   
      image: ivanduque0/telegrambot:V1.0
      
      restart: always
      
      command: python3 codigo.py
      
      volumes:
         - ./botelegram:/app
         
      env_file:
         - .env.manager
      
      depends_on:
         - postgres

   facerecognition1:

      image: ivanduque0/dockermpfrpsy:v1
      
      environment:
         - DISPLAY=unix$DISPLAY
         - HOST_STREAM=http://192.168.4.10:8080/?action=stream
         - RAZON=
         - ACCESO=1
      
      restart: always
      
      env_file:
         - .env.recognition
      
      volumes:
         - ./facerecognition:/app
         - ./dbmanagerfotos/media/personas:/app/personas
         - /tmp/.X11-unix:/tmp/.X11-unix
         - /tmp/.docker.xauth:/tmp/.docker.xauth
         
      privileged: true
      
      depends_on:
         - postgres
   
   facerecognition2:

      image: ivanduque0/dockermpfrpsy:v1
      
      environment:
         - DISPLAY=unix$DISPLAY
         - HOST_STREAM=
         - RAZON=
         - ACCESO=2
      
      restart: always
      
      env_file:
         - .env.recognition
      
      volumes:
         - ./facerecognition:/app
         - ./dbmanagerfotos/media/personas:/app/personas
         - /tmp/.X11-unix:/tmp/.X11-unix
         - /tmp/.docker.xauth:/tmp/.docker.xauth

   facerecognition3:

      image: ivanduque0/dockermpfrpsy:v1
      
      environment:
         - DISPLAY=unix$DISPLAY
         - HOST_STREAM=
         - RAZON=
         - ACCESO=3
      
      restart: always

      env_file:
         - .env.recognition
      
      volumes:
         - ./facerecognition:/app
         - ./dbmanagerfotos/media/personas:/app/personas
         - /tmp/.X11-unix:/tmp/.X11-unix
         - /tmp/.docker.xauth:/tmp/.docker.xauth
         
      privileged: true
      
      depends_on:
         - postgres

   facerecognition4:

      image: ivanduque0/dockermpfrpsy:v1
      
      environment:
         - DISPLAY=unix$DISPLAY
         - HOST_STREAM=
         - RAZON=
         - ACCESO=4
      
      restart: always
      
      env_file:
         - .env.recognition
      
      volumes:
         - ./facerecognition:/app
         - ./dbmanagerfotos/media/personas:/app/personas
         - /tmp/.X11-unix:/tmp/.X11-unix
         - /tmp/.docker.xauth:/tmp/.docker.xauth
         
      privileged: true
      
      depends_on:
         - postgres
   
   antispoofing1:
   
      image: ivanduque0/antispoofing:V1.1
      
      restart: always
      
      command: python3 codigo.py
      
      environment:
         - HOSTSNAPSHOOT=http://192.168.20.148:8080/?action=snapshot
         - ACCESO=1
         
      env_file:
         - .env.manager
      
      depends_on:
         - postgres

   antispoofing2:
   
      image: ivanduque0/antispoofing:V1.1
      
      restart: always
      
      command: python3 codigo.py
      
      environment:
         - HOSTSNAPSHOOT=
         - ACCESO=2
         
      env_file:
         - .env.manager
      
      depends_on:
         - postgres

   antispoofing3:
   
      image: ivanduque0/antispoofing:V1.1
      
      restart: always
      
      command: python3 codigo.py
      
      environment:
         - HOSTSNAPSHOOT=
         - ACCESO=3
         
      env_file:
         - .env.manager
      
      depends_on:
         - postgres
   
   antispoofing4:
   
      image: ivanduque0/antispoofing:V1.1
      
      restart: always
      
      command: python3 codigo.py
      
      environment:
         - HOSTSNAPSHOOT=
         - ACCESO=4
         
      env_file:
         - .env.manager
      
      depends_on:
         - postgres

   

   
      
   
