services:

   postgres:
   
      image: postgres:14-alpine
      
      container_name: postgres

      restart: always

      ports:
         - 44:5432
         
      volumes:
         - ./postgresdata:/var/lib/postgresql/data
         
      env_file:
         - .env
   
   db:
      build: .
      volumes:
         - ./db:/app

      command: python3 codigo.py

      env_file:
         - .env

      depends_on:
         - postgres

   server:
   
      build: .

      container_name: server
      
      restart: always
      
      command: python3 codigo.py
      
      volumes:
         - ./servidor:/app

      ports:
         - 43157:43157
         
      env_file:
         - .env
      
      depends_on:
         - postgres

   update_db:

      build: .

      container_name: update_db

      restart: always

      command: python3 update_db.py

      volumes:
         - ./scripts:/app

      env_file:
         - .env

      depends_on:
         - postgres