version: '3.3'

services:

   postgres:
   
      image: postgres:14-alpine
      
      container_name: postgres

      restart: always

      ports:
         - 44:5432
         
      volumes:
         - ./postgresdata:/var/lib/postgresql/data
         
      env_file:
         - .env.postgres
   
   dbmaker:
   
      image: ivanduque0/dbmakermanager:V0.3
      
      volumes:
         - ./dbmaker:/app
         
      command: python3 codigo.py
         
      env_file:
         - .env.manager
         
      depends_on:
         - postgres

   dbmanagerall:
   
      image: ivanduque0/dbmakermanager:V0.3

      container_name: dbmanagerall
      
      restart: always
      
      command: python3 codigo.py
      
      volumes:
         - ./allmanager:/app
         
      env_file:
         - .env.manager
      
      depends_on:
         - postgres
         
   telegrambot:
   
      image: ivanduque0/telegrambot:V1.0

      container_name: telegrambot
      
      restart: always
      
      command: python3 codigo.py
      
      volumes:
         - ./botelegram:/app
         
      env_file:
         - .env.manager
      
      depends_on:
         - postgres
   
   aperturas:
   
      image: ivanduque0/telegrambot:V1.0

      container_name: aperturas
      
      restart: always
      
      command: python3 codigo.py
      
      volumes:
         - ./aperturas:/app
         
      env_file:
         - .env.manager
      
      depends_on:
         - postgres

   wifilocal:
   
      image: ivanduque0/telegrambot:V1.0

      container_name: wifilocal
      
      restart: always
      
      command: python3 codigo.py
      
      volumes:
         - ./servidorlocalwifi:/app

      ports:
         - 43157:43157
         
      env_file:
         - .env.manager
      
      depends_on:
         - postgres

   ping:
   
      image: ivanduque0/dbmakermanager:V0.3

      container_name: ping
      
      restart: always
      
      command: python3 codigo.py
      
      volumes:
         - ./pingdispositivos:/app
         
      env_file:
         - .env.manager
      
      depends_on:
         - postgres

   facerecognition1:

      image: ivanduque0/dockermpfrpsy:v1

      container_name: facerecognition1
      
      environment:
         #- DISPLAY=unix$DISPLAY
         - HOST_STREAM=http://192.168.21.117:8080/?action=stream
         - RAZON=
         - URL_ACCESO=
         - ACCESO=1
      
      restart: always
      
      env_file:
         - .env.recognition
      
      volumes:
         - ./facerecognition:/app
         #- ./dbmanagerfotos/media/personas:/app/personas
         - ./allmanager/media/personas:/app/personas
         #- /tmp/.X11-unix:/tmp/.X11-unix
         #- /tmp/.docker.xauth:/tmp/.docker.xauth
         
      privileged: true
      
      depends_on:
         - postgres

   antispoofing1:
   
      image: ivanduque0/antispoofingyolo:V0.1

      container_name: antispoofing1
      
      restart: always
      
      command: python3 codigo/detect2.py --weights modeloYOLOV5.pt --img 416 --conf 0.5
      
      environment:
         - HOSTSNAPSHOOT=http://192.168.21.117:8080/?action=snapshot
         - ACCESO=1
         
      env_file:
         - .env.manager

      volumes:
         - ./antispoofing:/usr/src/app/codigo
      
      depends_on:
         - postgres
   
   facerecognition2:

      image: ivanduque0/dockermpfrpsy:v1

      container_name: facerecognition2
      
      environment:
         #- DISPLAY=unix$DISPLAY
         - HOST_STREAM=http://192.168.21.117:8080/?action=stream
         - RAZON=
         - URL_ACCESO=
         - ACCESO=2
      
      restart: always
      
      env_file:
         - .env.recognition
      
      volumes:
         - ./facerecognition:/app
         - ./allmanager/media/personas:/app/personas
         #- /tmp/.X11-unix:/tmp/.X11-unix
         #- /tmp/.docker.xauth:/tmp/.docker.xauth

   antispoofing2:
   
      image: ivanduque0/antispoofingyolo:V0.1

      container_name: antispoofing2
      
      restart: always
      
      command: python3 codigo/detect2.py --weights modeloYOLOV5.pt --img 416 --conf 0.3
      
      environment:
         - HOSTSNAPSHOOT=http://192.168.21.117:8080/?action=snapshot
         - ACCESO=2
         
      env_file:
         - .env.manager

      volumes:
         - ./antispoofing:/usr/src/app/codigo
      
      depends_on:
         - postgres

   facerecognition3:

      image: ivanduque0/dockermpfrpsy:v1

      container_name: facerecognition3
      
      environment:
         #- DISPLAY=unix$DISPLAY
         - HOST_STREAM=http://192.168.21.117:8080/?action=stream
         - RAZON=
         - URL_ACCESO=
         - ACCESO=3
      
      restart: always

      env_file:
         - .env.recognition
      
      volumes:
         - ./facerecognition:/app
         - ./allmanager/media/personas:/app/personas
         #- /tmp/.X11-unix:/tmp/.X11-unix
         #- /tmp/.docker.xauth:/tmp/.docker.xauth
         
      privileged: true
      
      depends_on:
         - postgres

   antispoofing3:
   
      image: ivanduque0/antispoofingyolo:V0.1

      container_name: antispoofing3
      
      restart: always
      
      command: python3 codigo/detect2.py --weights modeloYOLOV5.pt --img 416 --conf 0.3
      
      environment:
         - HOSTSNAPSHOOT=http://192.168.21.117:8080/?action=snapshot
         - ACCESO=3
         
      env_file:
         - .env.manager

      volumes:
         - ./antispoofing:/usr/src/app/codigo
      
      depends_on:
         - postgres

   facerecognition4:

      image: ivanduque0/dockermpfrpsy:v1

      container_name: facerecognition4
      
      environment:
         #- DISPLAY=unix$DISPLAY
         - HOST_STREAM=http://192.168.21.117:8080/?action=stream
         - RAZON=
         - URL_ACCESO=
         - ACCESO=4
      
      restart: always
      
      env_file:
         - .env.recognition
      
      volumes:
         - ./facerecognition:/app
         - ./allmanager/media/personas:/app/personas
         #- /tmp/.X11-unix:/tmp/.X11-unix
         #- /tmp/.docker.xauth:/tmp/.docker.xauth
         
      privileged: true
      
      depends_on:
         - postgres
   
   antispoofing4:
   
      image: ivanduque0/antispoofingyolo:V0.1

      container_name: antispoofing4
      
      restart: always
      
      command: python3 codigo/detect2.py --weights modeloYOLOV5.pt --img 416 --conf 0.3
      
      environment:
         - HOSTSNAPSHOOT=http://192.168.21.117:8080/?action=snapshot
         - ACCESO=4
         
      env_file:
         - .env.manager

      volumes:
         - ./antispoofing:/usr/src/app/codigo
      
      depends_on:
         - postgres


   # dbmanagerfotos:
   
   #    image: ivanduque0/dbmakermanager:V0.3
      
   #    restart: always
      
   #    command: python3 codigo.py
      
   #    volumes:
   #       - ./dbmanagerfotos:/app
         
   #    env_file:
   #       - .env.manager
         
   #    depends_on:
   #       - postgres
         
   # dbmanagerusuarios:
   
   #    image: ivanduque0/dbmakermanager:V0.3
      
   #    restart: always
      
   #    command: python3 codigo.py
      
   #    volumes:
   #       - ./dbmanagerusuarios:/app
         
   #    env_file:
   #       - .env.manager
      
   #    depends_on:
   #       - postgres
         
   # dbmanagerhorarios:
   
   #    image: ivanduque0/dbmakermanager:V0.3
      
   #    restart: always
      
   #    command: python3 codigo.py
      
   #    volumes:
   #       - ./dbmanagerhorarios:/app
         
   #    env_file:
   #       - .env.manager
      
   #    depends_on:
   #       - postgres
         
   # dbmanagerinteracciones:
   
   #    image: ivanduque0/dbmakermanager:V0.3
      
   #    restart: always
      
   #    command: python3 codigo.py
      
   #    volumes:
   #       - ./dbmanagerinteracciones:/app
         
   #    env_file:
   #       - .env.manager
      
   #    depends_on:
   #       - postgres

   # dbmanagerid:
   
   #    image: ivanduque0/dbmakermanager:V0.3
      
   #    restart: always
      
   #    command: python3 codigo.py
      
   #    volumes:
   #       - ./dbmanagertelegramid:/app
         
   #    env_file:
   #       - .env.manager
      
   #    depends_on:
   #       - postgres